# HEALTHCHECK sales
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: sales-back-config
spec:
  healthCheck:
    checkIntervalSec: 60
    port: 8001
    type: HTTP
    requestPath: /sales/health
---
apiVersion: v1
kind: Service
metadata:
  name: sales-db
spec:
  selector:
    app: sales-db
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: sales-api
  annotations:
    cloud.google.com/backend-config: '{"default": "sales-back-config"}'
spec:
  selector:
    app: sales-api
  ports:
  - port: 8001
    targetPort: 8001