# sales DB
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sales-db
  template:
    metadata:
      labels:
        app: sales-db
    spec:
      containers:
      - name: sales-db
        image: postgres:latest
        env:
        - name: POSTGRES_USER
          value: sales
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: sales_db
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -d
            - $(POSTGRES_DB)
            - -U
            - $(POSTGRES_USER)
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        volumeMounts:
        - name: sales-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: sales-data
        persistentVolumeClaim:
          claimName: sales-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sales-db
spec:
  selector:
    app: sales-db
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sales-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# sales Broker Consumer
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-broker-consumer
  labels:
    app: sales-broker-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sales-broker-consumer
  template:
    metadata:
      labels:
        app: sales-broker-consumer
    spec:
      containers:
      - name: sales-broker-consumer
        image: us-central1-docker.pkg.dev/ccp-perspicapps/ccp-images/sales:latest
        command: ["python", "-u", "start_broker_consumer.py"]
        env:
        - name: DB_USER
          value: sales
        - name: DB_PASSWORD
          value: postgres
        - name: DB_HOST
          value: sales-db
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: sales_db
        - name: BROKER_HOST
          value: rabbitmq
        - name: CREATE_DELIVERY_TOPIC
          value: rpc_create_delivery
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
---
# sales API
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sales-api
  template:
    metadata:
      labels:
        app: sales-api
    spec:
      containers:
      - name: sales-api
        image: us-central1-docker.pkg.dev/ccp-perspicapps/ccp-images/sales:latest
        command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "9003"]
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        ports:
        - containerPort: 9003
        env:
        - name: DB_USER
          value: sales
        - name: DB_PASSWORD
          value: postgres
        - name: DB_HOST
          value: sales-db
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: sales_db
        - name: BROKER_HOST
          value: rabbitmq
        - name: CREATE_DELIVERY_TOPIC
          value: rpc_create_delivery
        livenessProbe:
          httpGet:
            path: /sales/health
            port: 9003
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 1
          failureThreshold: 2
---
# HEALTHCHECK sales
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: sales-config
spec:
  healthCheck:
    checkIntervalSec: 60
    port: 9003
    type: HTTP
    requestPath: /sales/health
---
apiVersion: v1
kind: Service
metadata:
  name: sales-api
  annotations:
    cloud.google.com/backend-config: '{"default": "sales-config"}'
spec:
  selector:
    app: sales-api
  ports:
  - port: 9003
    targetPort: 9003
