apiVersion: v1
kind: ConfigMap
metadata:
  name: sales-config
data:
  DB_HOST: "sales-db"
  DB_PORT: "5432"
  DB_NAME: "sales_db"
  BROKER_HOST: "rabbitmq"
  RESERVE_ITEMS_TOPIC: "rpc_reserve_items"
---
apiVersion: v1
kind: Secret
metadata:
  name: sales-secrets
type: Opaque
data:
  DB_USER: c2FsZXM= # sales base64 encoded
  DB_PASSWORD: cG9zdGdyZXM=  # postgres (base64 encoded)