apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- k8s-sales-deploy.yml

images:
- name: us-central1-docker.pkg.dev/ccp-perspicapps/ccp-images/sales
  newName: us-central1-docker.pkg.dev/ccp-perspicapps/ccp-images/sales
  newTag: latest