# HEALTHCHECK inventory
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: inventory-back-config
spec:
  healthCheck:
    checkIntervalSec: 60
    port: 8001
    type: HTTP
    requestPath: /inventory/health
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-db
spec:
  selector:
    app: inventory-db
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-api
  annotations:
    cloud.google.com/backend-config: '{"default": "inventory-back-config"}'
spec:
  selector:
    app: inventory-api
  ports:
  - port: 8001
    targetPort: 8001
