# inventory DB
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inventory-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-db
  template:
    metadata:
      labels:
        app: inventory-db
    spec:
      containers:
      - name: inventory-db
        image: postgres:latest
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: inventory-secrets
              key: DB_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: inventory-secrets
              key: DB_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: inventory-config
              key: DB_NAME
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -d
            - $(POSTGRES_DB)
            - -U
            - $(POSTGRES_USER)
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        volumeMounts:
        - name: inventory-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: inventory-data
        persistentVolumeClaim:
          claimName: inventory-pvc
---
# inventory Broker Consumer
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-broker-consumer
  labels:
    app: inventory-broker-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-broker-consumer
  template:
    metadata:
      labels:
        app: inventory-broker-consumer
    spec:
      containers:
      - name: inventory-broker-consumer
        image: us-central1-docker.pkg.dev/ccp-perspicapps/ccp-images/inventory:latest
        command: ["python", "-u", "start_broker_consumer.py"]
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: inventory-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: inventory-secrets
              key: DB_PASSWORD
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: inventory-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: inventory-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: inventory-config
              key: DB_NAME
        - name: BROKER_HOST
          valueFrom:
            configMapKeyRef:
              name: inventory-config
              key: BROKER_HOST
        - name: RESERVE_ITEMS_TOPIC
          valueFrom:
            configMapKeyRef:
              name: inventory-config
              key: RESERVE_ITEMS_TOPIC
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
---
# inventory API
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-api
  template:
    metadata:
      labels:
        app: inventory-api
    spec:
      containers:
      - name: inventory-api
        image: us-central1-docker.pkg.dev/ccp-perspicapps/ccp-images/inventory:latest
        command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        ports:
        - containerPort: 8001
          name: api-port
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: inventory-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: inventory-secrets
              key: DB_PASSWORD
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: inventory-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: inventory-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: inventory-config
              key: DB_NAME
        - name: BROKER_HOST
          valueFrom:
            configMapKeyRef:
              name: inventory-config
              key: BROKER_HOST
        - name: RESERVE_ITEMS_TOPIC
          valueFrom:
            configMapKeyRef:
              name: inventory-config
              key: RESERVE_ITEMS_TOPIC
        livenessProbe:
          httpGet:
            path: /inventory/health
            port: 8001
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 1
          failureThreshold: 2
      - name: inventory-socket
        image: us-central1-docker.pkg.dev/ccp-perspicapps/ccp-images/inventory:latest
        command: ["uvicorn", "start_socket_server:app", "--host", "0.0.0.0", "--port", "8006"]
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        ports:
        - containerPort: 8006
          name: socket-port
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: inventory-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: inventory-secrets
              key: DB_PASSWORD
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: inventory-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: inventory-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: inventory-config
              key: DB_NAME
        - name: BROKER_HOST
          valueFrom:
            configMapKeyRef:
              name: inventory-config
              key: BROKER_HOST
        livenessProbe:
          httpGet:
            path: /inventory/health
            port: 8006
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 1
          failureThreshold: 2
