apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-config
data:
  DB_HOST: "inventory-db"
  DB_PORT: "5432"
  DB_NAME: "inventory_db"
  BROKER_HOST: "rabbitmq"
  RESERVE_ITEMS_TOPIC: "rpc_reserve_items"
---
apiVersion: v1
kind: Secret
metadata:
  name: inventory-secrets
type: Opaque
data:
  DB_USER: aW52ZW50b3J5 # inventory base64 encoded
  DB_PASSWORD: cG9zdGdyZXM=  # postgres (base64 encoded)