# HEALTHCHECK logistic
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: logistic-back-config
spec:
  healthCheck:
    checkIntervalSec: 60
    port: 8001
    type: HTTP
    requestPath: /logistic/health
---
apiVersion: v1
kind: Service
metadata:
  name: logistic-db
spec:
  selector:
    app: logistic-db
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: logistic-api
  annotations:
    cloud.google.com/backend-config: '{"default": "logistic-back-config"}'
spec:
  selector:
    app: logistic-api
  ports:
  - port: 80
    targetPort: 8001