apiVersion: v1
kind: ConfigMap
metadata:
  name: suppliers-config
data:
  DB_HOST: "suppliers-db"
  DB_PORT: "5432"
  DB_NAME: "suppliers_db"
  BROKER_HOST: "rabbitmq"
  RESERVE_ITEMS_TOPIC: "rpc_reserve_items"
  GCS_BUCKET_NAME: "ccp-files-storage"
  GOOGLE_APPLICATION_CREDENTIALS: "/etc/gcp/service-account-key.json"
---
apiVersion: v1
kind: Secret
metadata:
  name: suppliers-secrets
type: Opaque
data:
  DB_USER: c3VwcGxpZXJz # suppliers base64 encoded
  DB_PASSWORD: cG9zdGdyZXM=  # postgres (base64 encoded)