# suppliers DB
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: suppliers-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: suppliers-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: suppliers-db
  template:
    metadata:
      labels:
        app: suppliers-db
    spec:
      containers:
      - name: suppliers-db
        image: postgres:latest
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: suppliers-secrets
              key: DB_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: suppliers-secrets
              key: DB_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: suppliers-config
              key: DB_NAME
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -d
            - $(POSTGRES_DB)
            - -U
            - $(POSTGRES_USER)
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        volumeMounts:
        - name: suppliers-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: suppliers-data
        persistentVolumeClaim:
          claimName: suppliers-pvc
---
# suppliers Broker Consumer
apiVersion: apps/v1
kind: Deployment
metadata:
  name: suppliers-broker-consumer
  labels:
    app: suppliers-broker-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: suppliers-broker-consumer
  template:
    metadata:
      labels:
        app: suppliers-broker-consumer
    spec:
      containers:
      - name: suppliers-broker-consumer
        image: us-central1-docker.pkg.dev/ccp-perspicapps/ccp-images/suppliers:latest
        command: ["python", "-u", "start_broker_consumer.py"]
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: suppliers-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: suppliers-secrets
              key: DB_PASSWORD
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: suppliers-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: suppliers-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: suppliers-config
              key: DB_NAME
        - name: BROKER_HOST
          valueFrom:
            configMapKeyRef:
              name: suppliers-config
              key: BROKER_HOST
        - name: RESERVE_ITEMS_TOPIC
          valueFrom:
            configMapKeyRef:
              name: suppliers-config
              key: RESERVE_ITEMS_TOPIC
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
---
# suppliers API
apiVersion: apps/v1
kind: Deployment
metadata:
  name: suppliers-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: suppliers-api
  template:
    metadata:
      labels:
        app: suppliers-api
    spec:
      containers:
      - name: suppliers-api
        image: us-central1-docker.pkg.dev/ccp-perspicapps/ccp-images/suppliers:latest
        command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        ports:
        - containerPort: 8001
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: suppliers-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: suppliers-secrets
              key: DB_PASSWORD
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: suppliers-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: suppliers-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: suppliers-config
              key: DB_NAME
        - name: BROKER_HOST
          valueFrom:
            configMapKeyRef:
              name: suppliers-config
              key: BROKER_HOST
        - name: RESERVE_ITEMS_TOPIC
          valueFrom:
            configMapKeyRef:
              name: suppliers-config
              key: RESERVE_ITEMS_TOPIC
        - name: GCS_BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: suppliers-config
              key: GCS_BUCKET_NAME
        - name: GOOGLE_APPLICATION_CREDENTIALS
          valueFrom:
            configMapKeyRef:
              name: suppliers-config
              key: GOOGLE_APPLICATION_CREDENTIALS
        volumeMounts:
        - name: gcp-key-volume
          mountPath: /etc/gcp
          readOnly: true
        livenessProbe:
          httpGet:
            path: /suppliers/health
            port: 8001
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 1
          failureThreshold: 2
      volumes:
      - name: gcp-key-volume
        secret:
          secretName: gcp-bucket-sa-key
          items:
          - key: service-account-key.json
            path: service-account-key.json
