apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- k8s-suppliers-deploy.yml

images:
- name: us-central1-docker.pkg.dev/ccp-perspicapps/ccp-images/suppliers
  newName: us-central1-docker.pkg.dev/ccp-perspicapps/ccp-images/suppliers
  newTag: latest