apiVersion: v1
kind: ConfigMap
metadata:
  name: users-config
data:
  DB_HOST: "users-db"
  DB_PORT: "5432"
  DB_NAME: "users_db"
  BROKER_HOST: "rabbitmq"
  RESERVE_ITEMS_TOPIC: "rpc_reserve_items"
---
apiVersion: v1
kind: Secret
metadata:
  name: users-secrets
type: Opaque
data:
  DB_USER: dXNlcnM= # users base64 encoded
  DB_PASSWORD: cG9zdGdyZXM=  # postgres (base64 encoded)