# HEALTHCHECK users
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: users-back-config
spec:
  healthCheck:
    checkIntervalSec: 60
    port: 8001
    type: HTTP
    requestPath: /api/v1/users/health
---
apiVersion: v1
kind: Service
metadata:
  name: users-db
spec:
  selector:
    app: users-db
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: users-api
  annotations:
    cloud.google.com/backend-config: '{"default": "users-back-config"}'
spec:
  selector:
    app: users-api
  ports:
  - port: 80
    targetPort: 8001