apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- k8s-users-deploy.yml

images:
- name: us-central1-docker.pkg.dev/ccp-perspicapps/ccp-images/users
  newName: us-central1-docker.pkg.dev/ccp-perspicapps/ccp-images/users
  newTag: latest