name: Assign Project to Issues

on:
  issues:
    types: [opened]

jobs:
  assign_project:
    runs-on: ubuntu-latest
    steps:
    - name: Check for task label
      id: check_label
      run: |
        if ! gh issue view ${{ github.event.issue.number }} --json labels | jq -e '.labels | map(.name) | index("Tarea")'; then
          echo "Issue not created from the correct template." >&2
          exit 1
        fi

    - name: Assign issue to a project
      if: success()
      uses: actions-ecosystem/action-add-project-card@v1
      with:
        project_url: https://github.com/Perspicapps-CCP/CCP/projects/CCP-TAREAS
        column_name: "To do"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
