name: Assign Project to Issues

on:
  issues:
    types: [opened]

jobs:
  assign_project:
    runs-on: ubuntu-latest
    steps:
    - name: Check for task label
      id: check_label
      run: |
        if ! gh issue view ${{ github.event.issue.number }} --json labels | jq -e '.labels | map(.name) | index("Tarea")'; then
          echo "Issue not created from the correct template." >&2
          exit 1

    - name: Assign issue to a project
      if: success()
      run: |
        gh project item add --project-name "CCP-TAREAS" --column-name "To do" --issue-number ${{ github.event.issue.number }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Assign issue to creator
      if: success()
      run: |
        gh issue edit ${{ github.event.issue.number }} --add-assignee ${{ github.event.issue.user.login }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
